[tool.poetry]
name = "altmol"
version = "0.2.0"
description = ""
authors = ["Tagir Akhmetshin <tagirshin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rdkit = "^2023"
pandas = "^2"
altair = "^5"


[tool.poetry.group.dev.dependencies]
black = "^24"
jupyterlab = "^4"
ipywidgets = "^8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
